#!/usr/bin/env bash

# Print welcome message
echo ""
echo "╔═══════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                           ║"
echo "║      🥋 PLATAFORMA DE ANÁLISE TÁTICA DE JIU-JITSU - React 19 + Node      ║"
echo "║                                                                           ║"
echo "║      Uma solução completa para análise de atletas e adversários           ║"
echo "║                                                                           ║"
echo "╚═══════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📦 STACK INSTALADO:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ✅ Frontend:"
echo "     • React 19                  - UI moderna"
echo "     • Vite                      - Build ultra-rápido"
echo "     • React Router v6           - Roteamento"
echo "     • TailwindCSS               - Estilos responsivos"
echo "     • Recharts                  - Gráficos interativos"
echo "     • Axios                     - HTTP client"
echo ""
echo "  ✅ Backend:"
echo "     • Node.js/Express           - Server robusto"
echo "     • CORS                      - Segurança"
echo "     • UUID                      - IDs únicos"
echo "     • Nodemon                   - Dev com auto-reload"
echo ""

echo "📁 ESTRUTURA DO PROJETO:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  projeto analise atletas/"
echo "  ├── frontend/                   (React Vite + Tailwind)"
echo "  ├── server/                     (Express Node.js)"
echo "  ├── README.md                   (Documentação principal)"
echo "  ├── API.md                      (Documentação da API)"
echo "  ├── DEPLOY.md                   (Guia de deploy)"
echo "  ├── DEVELOPMENT.md              (Guia de desenvolvimento)"
echo "  └── ARCHITECTURE.md             (Arquitetura detalhada)"
echo ""

echo "🚀 PARA COMEÇAR:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Instalar dependências:"
echo "     $ cd frontend && npm install"
echo "     $ cd ../server && npm install"
echo ""
echo "  2. Iniciar servidor (Terminal 1):"
echo "     $ cd server && npm run dev"
echo ""
echo "  3. Iniciar frontend (Terminal 2):"
echo "     $ cd frontend && npm run dev"
echo ""
echo "  4. Abrir navegador:"
echo "     🌐 http://localhost:5173"
echo ""

echo "📋 PÁGINAS DISPONÍVEIS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  / (/)                          Dashboard com estatísticas"
echo "  /athletes                       Gerenciar atletas"
echo "  /athletes/:id                   Detalhe do atleta"
echo "  /opponents                      Gerenciar adversários"
echo "  /compare                        Comparar atleta x adversário"
echo "  /strategy                       Estratégia com IA"
echo ""

echo "🔌 API ENDPOINTS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Atletas:"
echo "    GET    /api/athletes           Listar todos"
echo "    GET    /api/athletes/:id       Obter um"
echo "    POST   /api/athletes           Criar"
echo "    PUT    /api/athletes/:id       Atualizar"
echo "    DELETE /api/athletes/:id       Deletar"
echo ""
echo "  Adversários: (mesma estrutura de /opponents)"
echo ""
echo "  IA:"
echo "    POST   /api/ai/strategy        Gerar estratégia"
echo ""

echo "✨ COMPONENTES PRINCIPAIS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ✓ Header                        Navegação principal"
echo "  ✓ AthleteCard                   Card com dados resumidos"
echo "  ✓ AthleteForm                   Formulário de cadastro"
echo "  ✓ StatsRadarChart               Gráfico radar de atributos"
echo "  ✓ StatsBarChart                 Gráfico de barras"
echo "  ✓ StatsLineChart                Gráfico de evolução"
echo "  ✓ CompareView                   Comparação lado a lado"
echo "  ✓ AiStrategyBox                 Estratégia com IA"
echo "  ✓ LoadingSpinner                Indicador de carregamento"
echo "  ✓ ErrorMessage                  Exibição de erros"
echo ""

echo "🔑 DADOS DE EXEMPLO:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Atletas:"
echo "    • João Silva        - Roxa, Guarda, 85kg, Cond: 85%"
echo "    • Maria Santos      - Azul, Passagem, 62kg, Cond: 75%"
echo "    • Carlos Oliveira   - Marrom, Pressão, 92kg, Cond: 80%"
echo ""
echo "  Adversários:"
echo "    • Pedro Ramos       - Marrom, Pressão, 90kg, Cond: 80%"
echo "    • Ana Costa         - Roxa, Explosão, 65kg, Cond: 90%"
echo ""

echo "📚 DOCUMENTAÇÃO:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Leia os arquivos para mais detalhes:"
echo "  📄 README.md           - Instruções gerais"
echo "  📄 API.md              - Documentação da API completa"
echo "  📄 DEPLOY.md           - Como fazer deploy"
echo "  📄 DEVELOPMENT.md      - Guia de desenvolvimento"
echo "  📄 ARCHITECTURE.md     - Visão técnica detalhada"
echo ""

echo "🛠️ FERRAMENTAS ÚTEIS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Testes de API: Use TESTING.http com REST Client do VSCode"
echo "  ou importe em Postman/Insomnia"
echo ""

echo "🎯 PRÓXIMOS PASSOS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ☐ Integrar com Supabase (banco de dados)"
echo "  ☐ Adicionar autenticação"
echo "  ☐ Implementar upload de vídeos"
echo "  ☐ Conectar IA real (OpenAI/Claude)"
echo "  ☐ Criar app mobile"
echo "  ☐ Deploy em produção"
echo ""

echo "📞 SUPORTE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ❓ Porta 5000 já em uso?"
echo "     → Mude em server/.env: PORT=5001"
echo ""
echo "  ❓ Erro de CORS?"
echo "     → Verifique VITE_API_URL em frontend/.env"
echo ""
echo "  ❓ Componentes não carregam?"
echo "     → Rode 'npm install' em ambos os diretórios"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "                        ✅ Projeto pronto para desenvolvimento!"
echo "                      🚀 Bora analisar alguns combates? 🥋"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
